// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacjaMedyczna.Model;

namespace SacjaMedyczna.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SacjaMedyczna.Model.DaneOsobowe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Imie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NumerDowodu")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("NumerTelefonu")
                        .HasColumnType("bigint");

                    b.Property<long>("Pesel")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("DaneOsosboweDB");
                });

            modelBuilder.Entity("SacjaMedyczna.Model.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ISBN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Ecample");
                });
#pragma warning restore 612, 618
        }
    }
}
